name: Validate Package Version

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: cad0p/semver-calver-release/validate-package-version@v1
