name: Validate Release PR

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: cad0p/semver-calver-release/validate-release-pr@v1
